name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest  # Or whatever your test/lint deps are
          # If you have a requirements.txt, also do:
          # pip install -r requirements.txt

      - name: Lint with PyLint
        run: |
          pylint **/*.py

      - name: Test with Pytest
        run: |
          pytest --cov=.  # if you want coverage
